### ISSUE TITLE
best approach for capturing extra user data?

### ISSUE THREAD

**Issue by bmidgley** [ocastalabs/CouchDB-Facebook-Authentication#4]
Hey, it's not clear how we should get additional user data from facebook like email, name, etc. I see I could modify the erlang code to save these on the user document in addition to the fb id, but do you have a simpler way in mind?

**Comment by ocasta** [comment]
We have a simple Couch external process that the client calls after login. This reads the fb_access_token from the user document in _users and then makes calls to the Facebook graph api. You can then return the info to the client or store it anywhere you want
