### ISSUE TITLE
_fb yields a 500 error plus {"error":"unknown_error","reason":"undef"} in iriscouch.com

### ISSUE THREAD

**Issue by joaojeronimo** [ocastalabs/CouchDB-Facebook-Authentication#7]
I didn't change anything in the configurations, just set my client_id and client_secret... I also added a vhost but I don't think that would make something wrong would it ?

If you want to look at it, here it is: http://ideas.workingondreams.com/_fb

**Comment by ocasta** [comment]
While Iriscouch may use this code, I have no knowledge of how they have configured it. Please take it up with them
